### ISSUE TITLE
uninitialized constant Trailblazer::Test

### ISSUE THREAD

**Issue by sorsaffari** [apotonick/gemgem-trbrb#24]
Hey @apotonick, I started reading your book today and so far been loving it! Thanks for writing it :)

On page 59, after writing the ThingIntegrationTest, I get the following error message from guard:

`gemgem_5/test/integration/test_thing.rb:3:in <top (required)>: uninitialized constant Trailblazer::Test (NameError)`

and the full stacktrace is:
```
/Users/soroushsaffari/gitkraken_apps/gemgem_5/test/integration/test_thing.rb:3:in `<top (required)>': uninitialized constant Trailblazer::Test (NameError)
	from /Users/soroushsaffari/.rvm/gems/ruby-2.3.1@rails5.0/gems/railties-5.0.0.1/lib/rails/test_unit/test_requirer.rb:11:in `block in require_files'
	from /Users/soroushsaffari/.rvm/gems/ruby-2.3.1@rails5.0/gems/railties-5.0.0.1/lib/rails/test_unit/test_requirer.rb:10:in `each'
	from /Users/soroushsaffari/.rvm/gems/ruby-2.3.1@rails5.0/gems/railties-5.0.0.1/lib/rails/test_unit/test_requirer.rb:10:in `require_files'
	from /Users/soroushsaffari/.rvm/gems/ruby-2.3.1@rails5.0/gems/railties-5.0.0.1/lib/rails/test_unit/minitest_plugin.rb:76:in `plugin_rails_init'
	from /Users/soroushsaffari/.rvm/gems/ruby-2.3.1@rails5.0/gems/minitest-5.10.1/lib/minitest.rb:80:in `block in init_plugins'
	from /Users/soroushsaffari/.rvm/gems/ruby-2.3.1@rails5.0/gems/minitest-5.10.1/lib/minitest.rb:78:in `each'
	from /Users/soroushsaffari/.rvm/gems/ruby-2.3.1@rails5.0/gems/minitest-5.10.1/lib/minitest.rb:78:in `init_plugins'
	from /Users/soroushsaffari/.rvm/gems/ruby-2.3.1@rails5.0/gems/minitest-5.10.1/lib/minitest.rb:129:in `run'
	from /Users/soroushsaffari/.rvm/gems/ruby-2.3.1@rails5.0/gems/railties-5.0.0.1/lib/rails/commands/test.rb:9:in `<top (required)>'
	from /Users/soroushsaffari/.rvm/gems/ruby-2.3.1@rails5.0/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:138:in `require_command!'
	from /Users/soroushsaffari/.rvm/gems/ruby-2.3.1@rails5.0/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:95:in `test'
	from /Users/soroushsaffari/.rvm/gems/ruby-2.3.1@rails5.0/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
	from /Users/soroushsaffari/.rvm/gems/ruby-2.3.1@rails5.0/gems/railties-5.0.0.1/lib/rails/commands.rb:18:in `<top (required)>'
	from /Users/soroushsaffari/gitkraken_apps/gemgem_5/bin/rails:9:in `<top (required)>'
	from /Users/soroushsaffari/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/soroushsaffari/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from -e:1:in `<main>'
```

I'm running on Rails 5.0 with Ruby 2.3.1 and here is what I have added to my Gemfile:

```
...
gem "trailblazer-rails"
gem "trailblazer-loader"
gem "reform", "~> 2.1.0"

group :test do
  gem "minitest-spec-rails"
  gem "minitest-rails-capybara"
  gem "minitest-line"

  gem 'guard'
  gem 'guard-minitest'
end
...
```

**Comment by sorsaffari** [comment]
In case anyone else experiences the same problem, I managed to resolve this by adding 

`require "trailblazer/rails/test/integration"`

to test_helper.rb
